#ifndef ENGINE_ENGINECONSTANTS_H
#define ENGINE_ENGINECONSTANTS_H

#define NOTIFY_TAG_QUIT_APPLICATION 1

#define NOTIFY_TAG_SET_MESSAGE_TEMPORARY 101
#define NOTIFY_TAG_SET_MESSAGE_PERMANENT 102



#endif //ENGINE_ENGINECONSTANTS_H
